sonar.projectKey=ekaterinachmil_php-project-57
sonar.organization=ekaterinachmil
sonar.sources=app,config,database,resources,routes
sonar.tests=tests
sonar.php.tests.reportPath=tests/report.xml
sonar.php.coverage.reportPaths=tests/coverage.xml
