sonar.projectKey=ekaterinachmil_php-project-57
sonar.organization=ekaterinachmil
sonar.projectName=php-project-57
sonar.sources=app,config,database,resources,routes
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.php.tests.reportPaths=tests/report.xml
sonar.php.coverage.reportPaths=tests/coverage.xml
